name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # Pull LFS files

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Set up Git user
        run: |
          git config --global user.email "fahmiyacm@gmail.com"
          git config --global user.name "Fahmiyacm"

      - name: Track binary files with LFS
        run: |
          git lfs track "faiss_index/*.faiss"
          git lfs track "faiss_index/*.pkl"
          git lfs track "recommender_model.pth"
          git lfs track "Menubook/*.jpeg"
          git add .gitattributes
          git commit -m "Track binary files with Git LFS" || echo "No changes to commit"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug File Presence
        run: |
          ls -lR .
          git lfs ls-files

      - name: Verify HF_TOKEN
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set or empty"
            exit 1
          else
            echo "HF_TOKEN is set"
          fi

      - name: Clone Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/Fahmiyacm/shawarma_customer_app hf_space

      - name: Sync Files (excluding .git & Screenshots)
        run: |
          rsync -av --exclude=.git --exclude=hf_space --exclude=Screenshots ./ hf_space/

      - name: Commit & Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf_space
          git lfs install
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes to commit"
          git push https://Fahmiyacm:$HF_TOKEN@huggingface.co/spaces/Fahmiyacm/shawarma_customer_app HEAD:main
