name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true  # to fetch LFS files like model, images

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove Screenshot Folder (Skip Upload to HF)
        run: |
          rm -rf screenshots

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "fahmiyacm@gmail.com"
          git config --global user.name "Fahmiyacm"
          
          # Clone your space repo
          git clone https://huggingface.co/spaces/Fahmiyacm/shawarma_customer_app hf_space
          cp -r * hf_space/
          cd hf_space
          git add .
          git commit -m "Auto deploy from GitHub"
          git push https://huggingface.co/Fahmiyacm:${HF_TOKEN}@huggingface.co/spaces/Fahmiyacm/shawarma_customer_app main
