name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # Fetch LFS files like model, images

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug File Presence
        run: |
          ls -lR .
          git lfs ls-files

      - name: Verify HF_TOKEN
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set or empty"
            exit 1
          else
            echo "HF_TOKEN is set"
          fi

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "fahmiyacm@gmail.com"
          git config --global user.name "Fahmiyacm"
          git clone https://huggingface.co/spaces/Fahmiyacm/shawarma_customer_app hf_space
          cd hf_space
          git lfs fetch --all
          git lfs checkout
          rsync -av --exclude=.git --exclude=hf_space --exclude=Screenshots ../* .
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes to commit"
          git push https://$HF_TOKEN@huggingface.co/spaces/Fahmiyacm/shawarma_customer_app main